### ISSUE TITLE
Serverengine logging threads livelock

### ISSUE THREAD

**Issue by jondot** [fluent/serverengine#21]
Hi,
We have bumped into a livelock (100% utilization of a core), with serverengine > 1.5.5, and I was able to narrow it down to exactly these lines:

https://github.com/fluent/serverengine/blob/master/lib/serverengine/server.rb#L110..L112

It seems reopening STDOUT/ERR causes some sort of a race condition and livelock? I'm not sure.

I have worked around this by specifying 'false' explicitly for both `:log_stdout` and `:log_stderr` from Sneakers. This wouldn't trigger the rewiring of output and work around this issue.

I was hoping to get more information about if you know why this happens and what is recommended to do?

Thanks!

**Comment by AlexRiedler** [comment]
I think might be able to provide more context. I experienced this while using sneakers and attached the good old gdb!

My rb_backtraces are below for the threads that were running.

They are all trying to shutdown, I am not sure if that is the same case as you @jondot; but might be related.

### Thread 1
```ruby
from /2.2.0/bin/sneakers:23:in `<main>'
from /2.2.0/bin/sneakers:23:in `load'
from /2.2.0/gems/sneakers-1.0.4/bin/sneakers:5:in `<top (required)>'
from /2.2.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
from /2.2.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
from /2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
from /2.2.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
from /2.2.0/gems/sneakers-1.0.4/lib/sneakers/cli.rb:93:in `work'
from /2.2.0/gems/sneakers-1.0.4/lib/sneakers/runner.rb:12:in `run'
from /2.2.0/gems/serverengine-1.5.10/lib/serverengine/daemon.rb:90:in `run'
from /2.2.0/gems/serverengine-1.5.10/lib/serverengine/daemon.rb:101:in `main'
from /2.2.0/gems/serverengine-1.5.10/lib/serverengine/server.rb:88:in `main'
from /2.2.0/gems/serverengine-1.5.10/lib/serverengine/multi_process_server.rb:40:in `run'
from /2.2.0/gems/serverengine-1.5.10/lib/serverengine/multi_worker_server.rb:56:in `run'
from /2.2.0/gems/serverengine-1.5.10/lib/serverengine/multi_process_server.rb:89:in `wait_tick'
```

### Thread 2
```ruby
from /ruby/2.2.0/bin/sneakers:23:in `<main>'
from /ruby/2.2.0/bin/sneakers:23:in `load'
from /ruby/2.2.0/gems/sneakers-1.0.4/bin/sneakers:5:in `<top (required)>'
from /ruby/2.2.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
from /ruby/2.2.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
from /ruby/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
from /ruby/2.2.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
from /ruby/2.2.0/gems/sneakers-1.0.4/lib/sneakers/cli.rb:93:in `work'
from /ruby/2.2.0/gems/sneakers-1.0.4/lib/sneakers/runner.rb:12:in `run'
from /ruby/2.2.0/gems/serverengine-1.5.10/lib/serverengine/daemon.rb:90:in `run'
from /ruby/2.2.0/gems/serverengine-1.5.10/lib/serverengine/daemon.rb:101:in `main'
from /ruby/2.2.0/gems/serverengine-1.5.10/lib/serverengine/server.rb:88:in `main'
from /ruby/2.2.0/gems/serverengine-1.5.10/lib/serverengine/multi_process_server.rb:40:in `run'
from /ruby/2.2.0/gems/serverengine-1.5.10/lib/serverengine/multi_worker_server.rb:56:in `run'
from /ruby/2.2.0/gems/serverengine-1.5.10/lib/serverengine/multi_process_server.rb:90:in `wait_tick'
```

### Thread 3
```ruby
from /ruby/2.2.0/bin/sneakers:23:in `<main>'
from /ruby/2.2.0/bin/sneakers:23:in `load'
from /ruby/2.2.0/gems/sneakers-1.0.4/bin/sneakers:5:in `<top (required)>'
from /ruby/2.2.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
from /ruby/2.2.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
from /ruby/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
from /ruby/2.2.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
from /ruby/2.2.0/gems/sneakers-1.0.4/lib/sneakers/cli.rb:93:in `work'
from /ruby/2.2.0/gems/sneakers-1.0.4/lib/sneakers/runner.rb:12:in `run'
from /ruby/2.2.0/gems/serverengine-1.5.10/lib/serverengine/daemon.rb:90:in `run'
from /ruby/2.2.0/gems/serverengine-1.5.10/lib/serverengine/daemon.rb:101:in `main'
from /ruby/2.2.0/gems/serverengine-1.5.10/lib/serverengine/server.rb:88:in `main'
from /ruby/2.2.0/gems/serverengine-1.5.10/lib/serverengine/multi_process_server.rb:40:in `run'
from /ruby/2.2.0/gems/serverengine-1.5.10/lib/serverengine/multi_worker_server.rb:56:in `run'
from /ruby/2.2.0/gems/serverengine-1.5.10/lib/serverengine/multi_process_server.rb:90:in `wait_tick'
from /ruby/2.2.0/gems/serverengine-1.5.10/lib/serverengine/process_manager.rb:212:in `tick'
from /ruby/2.2.0/gems/serverengine-1.5.10/lib/serverengine/process_manager.rb:212:in `each'
```

### Thread 4
```ruby
from /ruby/2.2.0/bin/sneakers:23:in `<main>'
from /ruby/2.2.0/bin/sneakers:23:in `load'
from /ruby/2.2.0/gems/sneakers-1.0.4/bin/sneakers:5:in `<top (required)>'
from /ruby/2.2.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
from /ruby/2.2.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
from /ruby/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
from /ruby/2.2.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
from /ruby/2.2.0/gems/sneakers-1.0.4/lib/sneakers/cli.rb:93:in `work'
from /ruby/2.2.0/gems/sneakers-1.0.4/lib/sneakers/runner.rb:12:in `run'
from /ruby/2.2.0/gems/serverengine-1.5.10/lib/serverengine/daemon.rb:90:in `run'
from /ruby/2.2.0/gems/serverengine-1.5.10/lib/serverengine/daemon.rb:101:in `main'
from /ruby/2.2.0/gems/serverengine-1.5.10/lib/serverengine/server.rb:88:in `main'
from /ruby/2.2.0/gems/serverengine-1.5.10/lib/serverengine/multi_process_server.rb:40:in `run'
from /ruby/2.2.0/gems/serverengine-1.5.10/lib/serverengine/multi_worker_server.rb:56:in `run'
from /ruby/2.2.0/gems/serverengine-1.5.10/lib/serverengine/multi_process_server.rb:90:in `wait_tick'
from /ruby/2.2.0/gems/serverengine-1.5.10/lib/serverengine/process_manager.rb:207:in `tick'
from /ruby/2.2.0/gems/serverengine-1.5.10/lib/serverengine/process_manager.rb:207:in `select'
from /ruby/2.2.0/gems/serverengine-1.5.10/lib/serverengine/multi_worker_server.rb:111:in `block in keepalive_workers'
```

**Comment by AlexRiedler** [comment]
Mine might not be related on second though; It appears it has to do with use of STDOUT... The documentation for serverengine says you have to pass "-", and I was passing STDOUT to Sneakers, which in result may have made everything go into a bad state.

**Comment by jondot** [comment]
You might be on to it!, it might be the STDOUT/"-" issue which causes the hangs. Should be easy to test with sneakers (just got to re-enable logging here https://github.com/jondot/sneakers/blob/master/lib/sneakers/runner.rb#L82-L83)

**Comment by repeatedly** [comment]
Thanks for the report.

> serverengine > 1.5.5

It means sneakers with serverengine 1.5.4 doesn't have this problem?
Could you paste the minimum code example?

**Comment by jondot** [comment]
Yes, 1.5.4 and also 1.5.5 doesn't have this problem.
Regarding a minimum code example, it will also require to set up a temporary environment (rabbitmq server). It is in my plans to use Docker to provide a self-contained environment in the upcoming weeks. 

For now any sneakers sample worker will demonstrate. To reproduce:

```
$ brew install rabbitmq && rabbitmq-server
-- or run RMQ via docker
$ git clone git@github.com:jondot/sneakers.git && cd sneakers
-- edit gemspec and force serverengine > 1.5.5
$ rake install && cd examples
$ sneakers work TitleScraper --require title_scraper.rb
-- sneakers should hang, not respond to ^C either
```

**Comment by AlexRiedler** [comment]
I had some time so I wrote a really small example:

```ruby
require 'serverengine'
require 'logger'

module Foo
  def self.logger
    @@logger ||= Logger.new(STDOUT)
  end
end

module WorkerGroup

  def run
    @stop = false
    until @stop
      Foo.logger.info("TESTING #{rand(5)}")
      puts "INTERNAL LOGGER: #{rand(10)}"
      sleep 1
    end
  end

  def stop
    @stop = true
  end
end

module MyServer
end

se = ServerEngine.create(MyServer, WorkerGroup, {
  daemonize: false,
  logger: Foo.logger,
  worker_type: 'process',
  workers: 4
})
se.run
```

basically if the logger you pass in is associated to STDOUT or STDERR it will not be a happy camper; since STDOUT and STDERR are reopened in general by the kernel AFAIK.

**Comment by frsyuki** [comment]
Setting `:logger` configuration was unexpected. To correctly handle it, `Server#initialize` can't simply use `ConfigLoader#logdev_from_config` because `ConfigLoader#logdev_from_config` doesn't consider `:logger`.

I guess (I'm not 100% sure) that a problem happens when:

* `config[:logger]` is set to a logger which writes messages to STDOUT (STDERR)
* `Server#initialize` sets `@log_stdout=true` (`@log_stderr=true`) because `ConfigLoader#logdev_from_config` doesn't consider :logger option.
* therefore `start_io_logging_thread(STDOUT)` is called.
* It starts a thread that reads data written to STDOUT (through pipe) and writes the data to STDOUT through `@logger`.
* depending on size of the data in pipe, it could cause busy loop or infinite block.

Could you try to apply #22?

**Comment by repeatedly** [comment]
How about above patch?

**Comment by frsyuki** [comment]
@repeatedly as along as I tested @AlexRiedler's code above, problem is fixed by #22. I think #22 is good to merge and close this issue. Could you review #22? And merge if you're good.

**Comment by AlexRiedler** [comment]
I think it's good to merge, I would want to write more tests on it before
I'm convinced it is a full fix, will reopen o/w I can look in tonight and
verify

**Comment by repeatedly** [comment]
Release v1.5.11. Please try!
