### ISSUE TITLE
serverengine v2.0.0 breaks permission changing on linux

### ISSUE THREAD

**Issue by neurogenesis** [fluent/serverengine#74]
Hello,

In looking to start fluentd, which uses serverengine, we were getting an EPERM error when trying to change privileges for the user/group running the fluentd agent.

https://github.com/fluent/serverengine/blob/4f15a3a3ecfe93ccb0eb95b6915d263e6bb37e9a/lib/serverengine/privilege.rb#L38

My guess is that the GID needs to be set before the UID. Once you change the effective UID, the process no longer has the permissions to modify its GID. Simply changing the order should fix this.

Some testing directly with ruby:

```
#!/usr/bin/env ruby

def show_permissions(msg)
  puts "#{msg}"
  puts "\t" << `id`
  puts
end

uid="fluentd"
gid="fluentd"

puts

show_permissions "current process privileges ..."

puts "changing uid to #{uid} ...\n"
Process::UID.change_privilege("fluentd")
show_permissions "new effective process privileges ..."

puts "changing gid to #{gid} ...\n"
Process::GID.change_privilege("fluentd")
show_permissions "new effective process privileges ..."
```

and the results with 
```
~ $ sudo ./change_privilege_uid_first.rb

current process privileges ...
        uid=0(root) gid=0(root) groups=0(root),1(bin),2(daemon),3(sys),4(adm),6(disk),10(wheel),11(floppy),26(tape),27(video)

changing uid to fluentd ...
new effective process privileges ...
        uid=999(fluentd) gid=0(root) groups=994(fluentd),0(root),1(bin),2(daemon),3(sys),4(adm),6(disk),10(wheel),11(floppy),26(tape),27(video)

changing gid to fluentd ...
./change_privilege_uid_first.rb:21:in `change_privilege': Operation not permitted (Errno::EPERM)
        from ./change_privilege_uid_first.rb:21:in `<main>'

~ $ sudo ./change_privilege_gid_first.rb

current process privileges ...
        uid=0(root) gid=0(root) groups=0(root),1(bin),2(daemon),3(sys),4(adm),6(disk),10(wheel),11(floppy),26(tape),27(video)

changing gid to fluentd ...
new effective process privileges ...
        uid=0(root) gid=994(fluentd) groups=0(root),1(bin),2(daemon),3(sys),4(adm),6(disk),10(wheel),11(floppy),26(tape),27(video)

changing uid to fluentd ...
new effective process privileges ...
        uid=999(fluentd) gid=994(fluentd) groups=994(fluentd),0(root),1(bin),2(daemon),3(sys),4(adm),6(disk),10(wheel),11(floppy),26(tape),27(video)
```

**Comment by tagomoris** [comment]
#75 was merged.d
